apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
  namespace: dify
data:
  CONSOLE_API_URL: ""
  APP_API_URL: ""
  SENTRY_DSN: ""
  NEXT_TELEMETRY_DISABLED: "0"
  TEXT_GENERATION_TIMEOUT_MS: "60000"
  CSP_WHITELIST: ""
  MARKETPLACE_API_URL: "https://marketplace.dify.ai"
  MARKETPLACE_URL: "https://marketplace.dify.ai"
  TOP_K_MAX_VALUE: ""
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: ""
  PM2_INSTANCES: "2"
  LOOP_NODE_MAX_COUNT: "100"
  MAX_TOOLS_NUM: "10"
  MAX_PARALLEL_LIMIT: "10"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-web
  namespace: dify
  labels:
    app: dify-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-web
  template:
    metadata:
      labels:
        app: dify-web
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      containers:
      - name: dify-web
        image: langgenius/dify-web:1.1.3
        envFrom:
        - configMapRef:
            name: web-env
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: dify
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: dify-web
  type: ClusterIP
  selector:
    app: dify-web