apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-env
  namespace: dify
data:
  DB_DATABASE: "dify_plugin"
  SERVER_PORT: "5002"
  SERVER_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  MAX_PLUGIN_PACKAGE_SIZE: "52428800"
  PPROF_ENABLED: "false"
  DIFY_INNER_API_URL: "http://dify-api.dify.svc.cluster.local:5001"
  DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_REMOTE_INSTALLING_HOST: "0.0.0.0"
  PLUGIN_REMOTE_INSTALLING_PORT: "5003"
  PLUGIN_WORKING_PATH: "/app/storage/cwd"
  FORCE_VERIFYING_SIGNATURE: "true"
  PYTHON_ENV_INIT_TIMEOUT: "120"
  PLUGIN_MAX_EXECUTION_TIMEOUT: "600"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-plugin-daemon-pvc
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-plugin-daemon
  namespace: dify
  labels:
    app: dify-plugin-daemon
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-plugin-daemon
  template:
    metadata:
      labels:
        app: dify-plugin-daemon
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      volumes:
      - name: dify-plugin-daemon-storage
        persistentVolumeClaim:
          claimName: dify-plugin-daemon-pvc
      containers:
      - name: dify-plugin-daemon
        image: langgenius/dify-plugin-daemon:0.0.3-local
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
          protocol: TCP
          name: debug-port
        - containerPort: 5002
          protocol: TCP
          name: service-port
        envFrom:
        - configMapRef:
            name: dify-env
        - configMapRef:
            name: plugin-env
        volumeMounts:
        - name: dify-plugin-daemon-storage
          mountPath: /app/storage

---
apiVersion: v1
kind: Service
metadata:
  name: dify-plugin-daemon
  namespace: dify
spec:
  type: ClusterIP
  selector:
    app: dify-plugin-daemon
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: debug-port
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: service-port