apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
  namespace: dify
data:
  SENTRY_DSN: ""
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  PLUGIN_MAX_PACKAGE_SIZE: "52428800"
  INNER_API_KEY_FOR_PLUGIN: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dify-api
  labels:
    app.kubernetes.io/instance: dify-api
    app: dify-api
  namespace: dify
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: dify-api
  selector:
    matchLabels:
      app: dify-api
  template:
    metadata:
      labels:
        app: dify-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
      - name: wait-for-dependencies
        image: busybox
        command: ["sh", "-c", "until nc -z dify-redis.dify.svc.cluster.local 6379 && nc -z dify-postgres.dify.svc.cluster.local 5432; do sleep 1; done"]
      containers:
      - name: dify-api
        image: langgenius/dify-api:1.1.3
        envFrom:
        - configMapRef:
            name: dify-env
        - configMapRef:
            name: api-env
        env:
        - name: MODE
          value: api
        - name: PLUGIN_REMOTE_INSTALL_HOST
          value: "dify-plugin-debug.dify.svc.cluster.local"
        - name: PLUGIN_REMOTE_INSTALL_PORT
          value: "5003"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: pg-password
        - name: CELERY_BROKER_URL
          value: "redis://:$(REDIS_PASSWORD)@dify-redis.dify.svc.cluster.local:6379/1"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dify-api-storage
          mountPath: /app/api/storage
      volumes:
      - name: dify-api-storage
        hostPath:
          path: /app/dify/api/data
          type: DirectoryOrCreate
  # volumeClaimTemplates:
  # - metadata:
  #     name: dify-api-storage
  #   spec:
  #     accessModes:
  #       - ReadWriteOnce
  #     storageClassName: "openebs-hostpath"
  #     resources:
  #       requests:
  #         storage: 1Gi
      
---
apiVersion: v1
kind: Service
metadata:
  name: dify-api
  namespace: dify
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: dify-api
  type: ClusterIP
  selector:
    app: dify-api