apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-sandbox-env
  namespace: dify
data:
  API_KEY: "dify-sandbox"
  GIN_MODE: "release"
  WORKER_TIMEOUT: "15"
  ENABLE_NETWORK: "true"
  SANDBOX_PORT: "8194"
  HTTP_PROXY: 'http://dify-ssrf.dify.svc.cluster.local:3128'
  HTTPS_PROXY: 'http://dify-ssrf.dify.svc.cluster.local:3128'

# 使用FQDN减少DNS查询
# Use FQDN to reduce DNS queries

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-sandbox
  namespace: dify
  labels:
    app: dify-sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-sandbox
  template:
    metadata:
      labels:
        app: dify-sandbox
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: dify-sandbox
        image: langgenius/dify-sandbox:0.2.10
        envFrom:
        - configMapRef:
            name: dify-sandbox-env
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - "curl"
            - "-f"
            - "http://localhost:8194/health"
        ports:
        - containerPort: 8194
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: dify-sandbox
  namespace: dify
spec:
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: dify-sandbox
  type: ClusterIP
  clusterIP: None
  selector:
    app: dify-sandbox